---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - default.example.com
  resources:
  - visitorapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - default.example.com
  resources:
  - visitorapps/finalizers
  verbs:
  - update
- apiGroups:
  - default.example.com
  resources:
  - visitorapps/status
  verbs:
  - get
  - patch
  - update
